# Generated by Django 4.2.1 on 2024-09-24 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_scraped',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
